### ISSUE TITLE
how to set up bot?

### ISSUE THREAD

**Issue by jbravo813** [d354n/Git-dsAutoBot#4]
Wish I knew how to set this up. After I download it I'm completely lost. I have NOX player. Any tips on a guide on how to set up the bot would be appreciated.

**Comment by d354n** [comment]
I am currently at work. I will make tutorial in the next 5-6 hours

Dapatkan Outlook untuk iOS<https://aka.ms/o0ukef>
________________________________

**Comment by d354n** [comment]
Btw have you install ankulua?

Dapatkan Outlook untuk iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jbravo813** [comment]
yes I installed but I'm not that computer literate lol. Any starting off tips from download would be helpful. Thanks!!

**Comment by d354n** [comment]
https://github.com/d354n/Git-dsAutoBot/wiki/Beginner-Tips
